### ISSUE TITLE
pylbm.Simulation doesn't work

### ISSUE THREAD

**Issue by NormKOALA** [pylbm/pylbm#160]
When I try to execute any demo code I have error on string with pylbm.Simulation

`AttributeError                            Traceback (most recent call last)
C:\Users\STANIS~1\AppData\Local\Temp/ipykernel_19288/258659169.py in <module>
    271     space_step = 1./256
    272     final_time = 10
--> 273     run(space_step, final_time)

C:\Users\STANIS~1\AppData\Local\Temp/ipykernel_19288/258659169.py in run(space_step, final_time, generator, sorder, with_plot)
    228     }
    229 
--> 230     sol = pylbm.Simulation(simu_cfg, sorder=sorder)
    231 
    232     if with_plot:

C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pylbm\simulation.py in __init__(self, dico, sorder, dtype, check_inverse, initialize)
     98         Monitor.set_size(domain_size)
     99 
--> 100         self.scheme = Scheme(dico, check_inverse=check_inverse, need_validation=False)
    101         if self.domain.dim != self.scheme.dim:
    102             log.error('Solution: the dimension of the domain and of the scheme are not the same\n')

C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pylbm\scheme.py in __init__(self, dico, check_inverse, need_validation)
    157 
    158         self._check_entry_size(scheme, 'relaxation_parameters')
--> 159         self.s = SymbolicVector([r for s in scheme for r in s['relaxation_parameters']])
    160 
    161         # TODO: add the possibility to have vectorial schemes when M matrix is defined

C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\sympy\matrices\repmatrix.py in __new__(cls, *args, **kwargs)
    315 
    316     def __new__(cls, *args, **kwargs):
--> 317         return cls._new(*args, **kwargs)
    318 
    319     @classmethod

C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pylbm\symbolic.py in _new(cls, copy, *args, **kwargs)
     38         # if cols != 1:
     39         #     raise ShapeError("SymVector input must be a list")
---> 40         self._mat = flat_list
     41         return self
     42 

AttributeError: can't set attribute`

**Comment by gouarin** [comment]
Hi @NormKOALA 
could you check the version of sympy? If it's 1.9, could you try with the 1.8 version?

**Comment by NormKOALA** [comment]
> Hi @NormKOALA could you check the version of sympy? If it's 1.9, could you try with the 1.8 version?

@gouarin, thanks for the quick response. This helped, but next error is came

`---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pylbm\generator\autowrap.py in _process_files(self, routine)
     80         try:
---> 81             retoutput = check_output(command, stderr=STDOUT)
     82         except CalledProcessError as e:

C:\DataScience\Anaconda3\envs\pylbm\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    414 
--> 415     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    416                **kwargs).stdout

C:\DataScience\Anaconda3\envs\pylbm\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    515         if check and retcode:
--> 516             raise CalledProcessError(retcode, process.args,
    517                                      output=stdout, stderr=stderr)

CalledProcessError: Command '['C:\\DataScience\\Anaconda3\\envs\\pylbm\\python.exe', 'C:\\Users\\STANIS~1\\AppData\\Local\\Temp\\tmpn2eczh89_sympy_compile\\build.py']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

CodeWrapError                             Traceback (most recent call last)
C:\Users\STANIS~1\AppData\Local\Temp/ipykernel_14092/258659169.py in <module>
    271     space_step = 1./256
    272     final_time = 10
--> 273     run(space_step, final_time)

C:\Users\STANIS~1\AppData\Local\Temp/ipykernel_14092/258659169.py in run(space_step, final_time, generator, sorder, with_plot)
    228     }
    229 
--> 230     sol = pylbm.Simulation(simu_cfg, sorder=sorder)
    231 
    232     if with_plot:

C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pylbm\simulation.py in __init__(self, dico, sorder, dtype, check_inverse, initialize)
    140             method.generate(self.container.sorder)
    141 
--> 142         self.generator.compile()
    143 
    144         self.init_type = dico.get('inittype', 'moments')

C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pylbm\generator\generator.py in compile(self)
     24 
     25     def compile(self):
---> 26         self.module = autowrap(self.routines.values(),
     27                                self.backend,
     28                                self.directory,

C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pylbm\generator\autowrap.py in autowrap(routines, backend, tempdir, generate, args, flags, verbose)
    154     code_wrapper = CodeWrapperClass(code_generator, tempdir, flags, generate, verbose)
    155 
--> 156     return code_wrapper.wrap_code(routines)

C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pylbm\generator\autowrap.py in wrap_code(self, routines)
     57                 self._prepare_files(routines)
     58                 self._generate_code(routines)
---> 59                 self._process_files(routines)
     60             if self.module_name in sys.modules:
     61                 sys.modules.pop(self.module_name)

C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pylbm\generator\autowrap.py in _process_files(self, routine)
     81             retoutput = check_output(command, stderr=STDOUT)
     82         except CalledProcessError as e:
---> 83             raise CodeWrapError(
     84                 "Error while executing command: %s. Command output is:\n%s" % (
     85                     " ".join(command), e.output.decode()))

CodeWrapError: Error while executing command: C:\DataScience\Anaconda3\envs\pylbm\python.exe C:\Users\STANIS~1\AppData\Local\Temp\tmpn2eczh89_sympy_compile\build.py. Command output is:
Traceback (most recent call last):
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pyximport\pyximport.py", line 214, in load_module
    so_path = build_module(module_name, pyxfilename, pyxbuild_dir,
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pyximport\pyximport.py", line 186, in build_module
    so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\_msvccompiler.py", line 327, in compile
    self.initialize()
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\_msvccompiler.py", line 224, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\_msvccompiler.py", line 126, in _get_vc_env
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\STANIS~1\AppData\Local\Temp\tmpn2eczh89_sympy_compile\build.py", line 4, in <module>
    import wrapped_module_0
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pyximport\pyximport.py", line 459, in load_module
    module = load_module(fullname, self.path,
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pyximport\pyximport.py", line 214, in load_module
    so_path = build_module(module_name, pyxfilename, pyxbuild_dir,
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pyximport\pyximport.py", line 186, in build_module
    so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\_msvccompiler.py", line 327, in compile
    self.initialize()
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\_msvccompiler.py", line 224, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\DataScience\Anaconda3\envs\pylbm\lib\distutils\_msvccompiler.py", line 126, in _get_vc_env
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
ImportError: Building module wrapped_module_0 failed: ['distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat\n']`

**Comment by gouarin** [comment]
You have to install a C compiler or change the code generator to bumpy.
The 1d examples should work.

**Comment by NormKOALA** [comment]
Thank you so much
