### ISSUE TITLE
 cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by mhechthz** [pylbm/pylbm#165]
Hi, during running a test example I get following  error:

```
The sympy.core.compatibility submodule is deprecated.

This module was only ever intended for internal use. Some of the functions
that were in this module are available from the top-level SymPy namespace,
i.e.,

    from sympy import ordered, default_sort_key

The remaining were only intended for internal SymPy use and should not be used
by user code.

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-sympy-core-compatibility
for details.

This has been deprecated since SymPy version 1.10. It
will be removed in a future version of SymPy.

  from sympy.core.compatibility import is_sequence
Traceback (most recent call last):
  File "C:\Micha\Programming\Python\LatticeBoltzmann\pylbmtest.py", line 85, in <module>
    'elements': [pylbm.Circle([.3, 0.5*(ymin+ymax)+2*dx], radius, label=2)],
  File "C:\Python39\lib\site-packages\pylbm\elements\circle.py", line 82, in __init__
    log.info(self.__str__())
  File "C:\Python39\lib\site-packages\pylbm\elements\circle.py", line 156, in __str__
    from ..jinja_env import env
  File "C:\Python39\lib\site-packages\pylbm\jinja_env.py", line 1, in <module>
    from jinja2 import Environment, PackageLoader, select_autoescape
  File "C:\Python39\lib\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Python39\lib\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Python39\lib\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Python39\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Python39\lib\site-packages\markupsafe\__init__.py)

```

**Comment by Sehmimul** [comment]
I had the same error. If you still have this issue,  can you try downgrading markupsafe to version 1.1.1 (`markupsafe==1.1.1`)? it worked in mine.

**Comment by gouarin** [comment]
Thanks for the update. I tried to reproduce this issue using `Karman_vortex_street.py` where there also is a circle but I can't reproduce it. I have `markupsafe==2.1.2`.

Could you give me the OS, the Python package manager used, and the script you try to run?

Thanks

**Comment by Sehmimul** [comment]
I ran the script in https://github.com/pylbm/pylbm/blob/master/notebooks/07_Von_Karman_vortex_street.ipynb on Mac M1 using Python 3.11.2, pip3 version 23.0.1. My markupsafe version was 1.1.1 also. Hope that helps!

**Comment by gouarin** [comment]
I made a new release (0.9.0).
Could you tell me if this issue is fixed with this new release?
Thanks
