### ISSUE TITLE
VTK error

### ISSUE THREAD

**Issue by haibianshifeng** [pylbm/pylbm#26]
E:\Anaconda3\python.exe C:/Users/LeiL/Desktop/pylbm_notebook-master/Corrections/01_advection.py
Traceback (most recent call last):
  File "C:/Users/LeiL/Desktop/pylbm_notebook-master/Corrections/01_advection.py", line 3, in <module>
    import pyLBM
  File "E:\Anaconda3\lib\site-packages\pyLBM\__init__.py", line 18, in <module>
    from .vtk import VTKFile
  File "E:\Anaconda3\lib\site-packages\pyLBM\vtk.py", line 3, in <module>
    from evtk.vtk import VtkFile, VtkRectilinearGrid
ModuleNotFoundError: No module named 'evtk'

Process finished with exit code 1

**Comment by gouarin** [comment]
How did you install pyLBM ? Using pip ?

**Comment by haibianshifeng** [comment]
Of  course.
Using pip install pyLBM

**Comment by gouarin** [comment]
We have some issues with the pyevtk package. 

Could you try to clone pylbm and then install it using the following command ?

```
pip install -r requirements.txt
python setup.py install 
```

**Comment by haibianshifeng** [comment]
Worse luck.

I use the following command.

pip install -r requirements.txt
python setup.py install 

However, the same errors appears.

**Comment by gouarin** [comment]
Ok. But now, we can change the behavior of how pyevtk is imported. 

Because the issue should be the name of the imported package.

Could you try in your Python interpreter to import pyevtk like

```
import pyevtk.hl
```

**Comment by haibianshifeng** [comment]
I use “import pyevtk.hl” to replace ‘’from evtk.vtk import VtkFile, VtkRectilinearGrid‘’ in vtk.py at line 3.

Then I run the example of advection.py in 1D file. Unfortunately, the errors appear as following.

E:\Anaconda3\python.exe C:/Users/LeiL/Desktop/pylbm-dockerfile/demo/1D/advection.py
Traceback (most recent call last):
  File "C:/Users/LeiL/Desktop/pylbm-dockerfile/demo/1D/advection.py", line 106, in <module>
    sol = run(dx, Tf, generator = pyLBM.generator.NumpyGenerator)
  File "C:/Users/LeiL/Desktop/pylbm-dockerfile/demo/1D/advection.py", line 73, in run
    sol = pyLBM.Simulation(dico, sorder=sorder) # build the simulation
  File "E:\Anaconda3\lib\site-packages\pyLBM\simulation.py", line 228, in __init__
    self.scheme.generate(sorder)
  File "E:\Anaconda3\lib\site-packages\pyLBM\scheme.py", line 676, in generate
    self.generator.get_module()
  File "E:\Anaconda3\lib\site-packages\pyLBM\generator\base.py", line 123, in get_module
    self.importmodule = importlib.import_module(self.modulename)
  File "E:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'C:\\Users\\LeiL\\'

**Comment by gouarin** [comment]
It seems that you work with the develop branch.

Could you see if you have the same issue with the master branch?

git checkout master
python setup.py install


Le 18 sept. 2017 7:33 AM, "haibianshifeng" <notifications@github.com> a
écrit :

**Comment by gouarin** [comment]
@haibianshifeng you can now install cleanly pylbm using the command line

```
conda install pylbm -c pylbm -c conda-forge
```
