### ISSUE TITLE
Execution issues

### ISSUE THREAD

**Issue by romainhild** [pylbm/pylbm#52]
I'm trying to test the library and I have several issues.
In the develop branch, I have the following error:
```
[11:46:24]hild@macbook-pro-de-romain-2:2D|develop*$ python Poiseuille_vec.py
Traceback (most recent call last):
  File "Poiseuille_vec.py", line 168, in <module>
    run(dx, Tf)
  File "Poiseuille_vec.py", line 135, in run
    sol = pylbm.Simulation(dico, sorder=sorder)
  File "build/bdist.macosx-10.13-x86_64/egg/pylbm/simulation.py", line 213, in __init__
  File "build/bdist.macosx-10.13-x86_64/egg/pylbm/scheme.py", line 794, in generate
  File "build/bdist.macosx-10.13-x86_64/egg/pylbm/generator/generator.py", line 12, in add_routine
  File "build/bdist.macosx-10.13-x86_64/egg/pylbm/generator/codegen.py", line 698, in make_routine
  File "build/bdist.macosx-10.13-x86_64/egg/pylbm/generator/codegen.py", line 260, in routine
  File "/usr/local/lib/python2.7/site-packages/sympy-1.1.2.dev0-py2.7.egg/sympy/utilities/codegen.py", line 293, in __init__
    raise TypeError("The first argument must be a sympy symbol.")
TypeError: The first argument must be a sympy symbol.
```

So I tried to use the master branch, and in it I had to change all calls to the module pyLBM to pylbm in minuscule otherwise it was not found. Once this was done, it is working.

I'm on mac and I installed the module with the `setup.py` script.

**Comment by romainhild** [comment]
ah indeed I'm using the development version of sympy.
Ok I'll test with the master branch for now, and we'll see if we need more.

Thanks for the quick reply!

**Comment by gouarin** [comment]
I close this issue but feel free to reopen it.

We also have a gitter channel https://gitter.im/pylbm/pylbm. 

At the moment this channel is empty but it could be a start to populate it ;)
